title: HUCHAO's Homepage
page-top-title: HUCHAO
top-section-bg-text: Humans may essentially be a kind of large language model
home-subtitle: 胡超&ENFJ
copyright-text: '&copy; HUCHAO 2023-2025. All Rights Reserved.'
